#version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: artifact-miner
    command: >
      /bin/sh -c "
      python src/db/wait_for_db.py &&
      python src/db/create_tables.py &&
      tail -f /dev/null"
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: