name: Python regression tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          sudo apt-get install -y build-essential libjpeg8-dev zlib1g-dev

      - name: Set up virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate  # Activating the virtual environment

      - name: Install Python dependencies
        run: |
          . venv/bin/activate  # Ensure virtualenv is activated
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install reportlab  # Install reportlab with pip

      - name: Debug: Print PYTHONPATH and test directory
        run: |
          echo "PYTHONPATH: $(pwd)/src"
          echo "Current Directory: $(pwd)"
          ls -l tests  # List the files in the tests directory to verify they exist

      - name: Run regression tests with PYTHONPATH
        run: |
          . venv/bin/activate  # Ensure virtualenv is activated
          export PYTHONPATH=$(pwd)/src  # Explicitly set PYTHONPATH
          pytest -v  # Run the tests with verbose output

      - name: Post Set up Python 3.11
        run: echo "Running post-setup tasks"
        if: always()  # Ensure this step runs even if tests fail
